### new user

POST http://localhost:5005/api/users HTTP/1.1
Content-Type: application/json

{
	"name": "auwal Staff",
	"email": "staff2@test.com",
	"password": "password",
	"password2": "password",
	"isStaff": true,
	"condition": {
		"diabetic": false,
		"hypertensive": false
	}
}

### get user
GET http://localhost:5005/api/auth HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJhdXdhbCIsImlkIjoiNjQ1ZmU2YTViZjYwMThmZjIyYzAxMDU0IiwiY29uZGl0aW9uIjp7ImRpYWJldGljIjpmYWxzZSwiaHlwZXJ0ZW5zaXZlIjp0cnVlfX0sImlhdCI6MTY4NDE4MzYzMSwiZXhwIjoxNjg0MTkwODMxfQ.htxdGO2IiDYWcZB4x44GcS9HN22BebDo7BSl9sK-Az8

### login user
post http://localhost:5005/api/auth HTTP/1.1
Content-Type: application/json

	{
	"email": "auwal@test.com",
	"password": "password"
	}

###

GET http://localhost:5005/api/auth HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJhdXdhbCBkaWFiZXRpYyIsImlkIjoiNjQ2YmJmMDNmNDViOWNhMGQwM2QzNGM1IiwiY29uZGl0aW9uIjp7Imh5cGVydGVuc2l2ZSI6ZmFsc2UsImRpYWJldGljIjp0cnVlfX0sImlhdCI6MTY4NDc4NDgzNywiZXhwIjoxNjg0NzkyMDM3fQ.SXU-VSn_hkPozCEsMlysGr4b2NS7sWlHIgKhv2JGfo0